### ISSUE TITLE
DeprecationWarning: 'GLOBAL' is deprecated, use 'global'

### ISSUE THREAD

**Issue by jiaxingzheng** [gavinengel/magic-globals#3]
relevant code:
`    if ( typeof GLOBAL.__filid !== 'undefined' && GLOBAL.__filid )`
`    {`
`          filid = GLOBAL.__filid;`
`    }`

**Comment by gavinengel** [comment]
Thank you for the head's up.  I'll fix this ASAP and push a new version.

**Comment by gavinengel** [comment]
Fixed in version 0.5.2

**Comment by AmitZoh** [comment]
This appears to still be open. I installed using 'npm install' and I received this error when using __fili
I looked at the source code here and GLOBAL still appears in uppercase.
